// Wave 5 Track F — dispatch, the token-only vendor portal, split awards, PDF.
//
//   node scripts/prove_wave5f_portal.mjs
//
// Requires: Postgres 55432, the API on 33001, the web on 33002.
//
// WHAT IS ACTUALLY BEING PROVEN
//   The feature list is long, so the harness is organised around the six claims
//   that would each be a real defect if false:
//
//   1. SMART LINE SPLITTING. A held line and a store-fulfilled line must not
//      reach a vendor, and what IS sent is the PENDING quantity. Proven by
//      building a PR with all three line kinds, issuing an RFQ, and reading the
//      pack back — not by reading the query.
//
//   2. TIME-BOUND TOKENS. A dispatch mints a link; a link past its expiry is
//      refused. The token is compared by SHA-256, so the raw value is not in the
//      database — proved by searching the column for it.
//
//   3. THE PORTAL IS A SANDBOX. The token sees only its own lines. Proven by
//      holding two tokens for two vendors and showing each cannot see the
//      other's lines or the PR.
//
//   4. THE EXCEL ROUND TRIP. A template generated by the server is parsed back
//      by the server and submitted. The file is a real ZIP/OOXML package, proved
//      by its magic bytes — not a renamed CSV.
//
//   5. REVISIONS DO NOT ERASE. Submit, submit again, and show v1 still readable
//      with its own price while v2 is live.
//
//   6. SPLIT AWARDS AND OFFLINE NEGOTIATION. One line, two different winners in
//      two rounds, with the first award still on record; and a phone-negotiated
//      rate that appends a version and lands in the immutable trail.
//
// EVERY MUTATION IS RESTORED IN `finally`. Audit rows cannot be restored — that
// is rule 5 working — and the count is reported rather than hidden.

import { spawnSync } from 'node:child_process';
import { existsSync, unlinkSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const API = process.env.API_BASE || 'http://127.0.0.1:33001';
const WEB = process.env.WEB_BASE || 'http://127.0.0.1:33002';
const CONTAINER = process.env.PG_CONTAINER || 'procurement-portal-db';
const REPO = resolve(fileURLToPath(import.meta.url), '..', '..');

let pass = 0, fail = 0, findings = 0;
const ok = (label, extra = '') => { pass++; console.log(`  PASS  ${label}${extra ? `  (${extra})` : ''}`); };
const bad = (label, detail) => { fail++; console.log(`  FAIL  ${label}\n        ${detail}`); };
const finding = (label, detail) => { findings++; console.log(`  FINDING  ${label}\n            ${detail}`); };
const eq = (label, actual, expected) => {
  if (String(actual) === String(expected)) ok(label, String(actual));
  else bad(label, `expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
};

function psql(sql) {
  const r = spawnSync(
    'docker',
    ['exec', '-i', CONTAINER, 'psql', '-U', 'proc', '-d', 'procurementDB',
      '-X', '-q', '-t', '-A', '-v', 'ON_ERROR_STOP=1'],
    { encoding: 'utf8', input: `SET app.bypass_rls = 'true';\n${sql}\n` },
  );
  const out = `${r.stdout || ''}`.trim();
  const err = `${r.stderr || ''}`.trim();
  if (r.status !== 0) throw new Error(`psql exited ${r.status}: ${err || out}\n--- sql ---\n${sql}`);
  return out;
}

function psqlExpectingFailure(sql) {
  const r = spawnSync(
    'docker',
    ['exec', '-i', CONTAINER, 'psql', '-U', 'proc', '-d', 'procurementDB',
      '-X', '-q', '-t', '-A', '-v', 'ON_ERROR_STOP=1'],
    { encoding: 'utf8', input: `SET app.bypass_rls = 'true';\n${sql}\n` },
  );
  return { failed: r.status !== 0, message: `${r.stderr || ''}`.trim() };
}

const lit = (s) => `'${String(s).replace(/'/g, "''")}'`;

async function api(path, { method = 'GET', token, body, raw, headers = {} } = {}) {
  const res = await fetch(`${API}${path}`, {
    method,
    headers: {
      ...(body ? { 'content-type': 'application/json' } : {}),
      ...(raw ? { 'content-type': raw.type } : {}),
      ...(token ? { authorization: `Bearer ${token}` } : {}),
      ...headers,
    },
    body: raw ? raw.body : (body ? JSON.stringify(body) : undefined),
  });
  const text = await res.text();
  let data = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = { raw: text }; }
  return { status: res.status, data, text };
}

const login = async (email) =>
  (await api('/auth/login', { method: 'POST', body: { email, password: 'demo' } })).data?.token;

console.log('\n=== Wave 5 Track F — dispatch, the token portal, split awards, PDF ===\n');

const procurement = await login('procurement@pakboxes.pk');
if (!procurement) { console.error('cannot log in — is the API up?'); process.exit(1); }

const auditBefore = Number(psql('SELECT count(*) FROM audit.audit_log;'));

// ─── fixtures ───────────────────────────────────────────────────────────────
let prId = null, rfqId = null, csId = null, holdLineId = null;
let tokenA = null, tokenB = null;
let docFile = null;
const createdVendorIds = [];

try {
  // ── 0. migration 040 is installed ───────────────────────────────────────
  console.log('--- 0. migration 040 is installed ---');
  for (const [t, rel] of [
    ['rfq_invitations_never_expires', 'proc.rfq_invitations'],
    ['rfq_invitations_expiry_after_invite', 'proc.rfq_invitations'],
    ['pr_lines_fulfilment_source', 'proc.pr_lines'],
    ['pr_lines_store_qty_consistent', 'proc.pr_lines'],
  ]) {
    const n = psql(`SELECT count(*) FROM pg_constraint WHERE conname=${lit(t)} AND conrelid=${lit(rel)}::regclass;`);
    eq(`constraint present: ${t}`, n, '1');
  }
  for (const tbl of ['core.email_outbox', 'proc.cs_line_awards', 'core.job_runs', 'proc.rfq_line_exclusions']) {
    const n = psql(`SELECT count(*) FROM information_schema.tables WHERE table_schema||'.'||table_name=${lit(tbl)};`);
    eq(`table present: ${tbl}`, n, '1');
  }
  const ttl = psql(`SELECT (value #>> '{}') FROM core.settings WHERE key='vendorPortalTokenHours';`);
  ok('the token lifetime is configuration, not a constant', `${ttl} hours`);

  // ── 1. smart line splitting ─────────────────────────────────────────────
  console.log('\n--- 1. proof: a held line and a store-fulfilled line never reach a vendor ---');
  // A PR with three deliberately different lines, so the filter is doing real
  // work rather than passing a pack that was already uniform.
  //
  // Cloned from a live PR rather than hand-inserted: purchase_requisitions
  // carries six NOT NULL foreign keys (department, cost centre, routing key,
  // workflow snapshot…) whose correct values are estate data, not harness
  // invention. Copying a real row keeps the fixture honest.
  prId = psql(`
    INSERT INTO proc.purchase_requisitions
      (pr_number, title, description, requester_user_id, department_id, cost_center_id,
       expense_type, required_by_date, status, routing_key, warehouse_check_required,
       estimated_amount, capex_amount, opex_amount, currency, scope, attachments,
       version, urgency, workflow_snapshot)
    SELECT 'PR-W5F-' || to_char(now(),'HH24MISS'), 'Harness split fixture', 'line-splitting proof',
           p.requester_user_id, p.department_id, p.cost_center_id,
           p.expense_type, (current_date + 30), 'IN_PROCUREMENT_REVIEW', p.routing_key, false,
           0, 0, 0, p.currency, p.scope, p.attachments, 1, p.urgency, p.workflow_snapshot
      FROM proc.purchase_requisitions p
     WHERE p.status = 'IN_PROCUREMENT_REVIEW'
     ORDER BY p.created_at DESC LIMIT 1
    RETURNING id;`).trim();
  if (!prId) { bad('the fixture PR could be created', 'no PR in procurement review to clone'); }

  const itemA = psql(`SELECT id FROM core.items WHERE active ORDER BY item_code LIMIT 1;`).trim();
  const itemB = psql(`SELECT id FROM core.items WHERE active ORDER BY item_code OFFSET 1 LIMIT 1;`).trim();
  const itemC = psql(`SELECT id FROM core.items WHERE active ORDER BY item_code OFFSET 2 LIMIT 1;`).trim();

  // gl_account and the UoM are estate data, so they are COPIED rather than typed
  // in. The UoM is read from core.uom itself because that FK is CASE-SENSITIVE
  // and core.items.uom is stored lowercase ('unit'), which does NOT satisfy it —
  // copying the item's own value fails the constraint.
  psql(`
    INSERT INTO proc.pr_lines
      (pr_id, line_no, item_id, quantity, uom, unit_price_est, gl_account,
       description, category, held, held_reason, fulfilment_source, store_fulfilled_qty)
    SELECT ${lit(prId)}::uuid, n.line_no, i.id, n.qty,
           COALESCE((SELECT code FROM core.uom WHERE code = 'EA'),
                    (SELECT code FROM core.uom ORDER BY code LIMIT 1)),
           100, i.gl_account,
           n.descr, i.category, n.held, n.reason, n.src, n.stock
      FROM (VALUES
        (1, 10::numeric, 'W5F line 1 — should be quoted',    'IG-OFC', false, NULL::text,  'PURCHASE',   NULL::numeric),
        (2,  5::numeric, 'W5F line 2 — HELD by the HOD',     'IG-OFC', true,  'Budget not released'::text, 'PURCHASE',   NULL::numeric),
        (3,  8::numeric, 'W5F line 3 — partly from stock',  'IG-OFC', false, NULL::text,  'STORE_STOCK', 3::numeric)
      ) AS n(line_no, qty, descr, category, held, reason, src, stock)
      JOIN core.items i ON i.id = ${lit(itemA)}::uuid;`);

  holdLineId = psql(`SELECT id FROM proc.pr_lines WHERE pr_id=${lit(prId)}::uuid AND line_no=2;`).trim();
  ok('fixture built with a clean line, a HELD line and a partly stock-fulfilled line');

  const issued = await api(`/pr/${prId}/rfq`, {
    method: 'POST', token: procurement, body: { title: 'W5F harness RFQ' },
  });
  if (issued.status >= 400) {
    bad('the RFQ is issued for the fixture PR', `status ${issued.status} ${issued.text.slice(0, 200)}`);
    rfqId = null;
  } else {
    rfqId = issued.data?.rfq?.id || issued.data?.id || null;
    // A 2xx that carries no id would otherwise let the cleanup block run a query
    // against the literal string "undefined" and mask the real failure behind a
    // UUID parse error.
    if (!rfqId || !/^[0-9a-f-]{36}$/i.test(String(rfqId))) {
      bad('the issued RFQ has a usable id', `response had none: ${issued.text.slice(0, 200)}`);
      rfqId = null;
    } else {
      ok('the RFQ is issued', issued.data?.rfq?.number || rfqId);
    }
  }

  if (rfqId) {
    const lines = psql(`
      SELECT string_agg(line_no || ':' || quantity::text, ',' ORDER BY line_no)
        FROM proc.rfq_lines WHERE rfq_id = ${lit(rfqId)}::uuid;`);
    ok('RFQ lines recorded', lines || '(none)');
    // numeric(18,3) renders as "10.000", so the comparison is NUMERIC. A string
    // match on '1:10' would fail on formatting and read as a filtering bug.
    const parsed = new Map(
      (lines || '').split(',').filter(Boolean).map((s) => {
        const [n, q] = s.split(':');
        return [Number(n), Number(q)];
      }),
    );
    if (parsed.get(1) === 10) ok('line 1 (clean) is on the RFQ at its full 10 units');
    else bad('line 1 (clean) is on the RFQ at its full 10 units', `quantity ${parsed.get(1)}`);

    if (parsed.has(2)) bad('the HELD line is NOT on the RFQ', `line 2 leaked at ${parsed.get(2)}`);
    else ok('the HELD line is NOT on the RFQ');

    // The stock line requested 8 with 3 already on the shelf, so the pack must
    // carry 5 — never 8, and never nothing. This is the "strictly pending
    // quantities" claim, and dropping the line entirely is the failure mode a
    // naive fulfilment_source filter produces.
    if (parsed.has(3) && parsed.get(3) === 5) {
      ok('the partly stock-fulfilled line is quoted at its PENDING remainder', '5 of 8');
    } else if (parsed.has(3)) {
      bad('the partly stock-fulfilled line is quoted at its PENDING remainder',
        `expected 5 (8 requested, 3 from stock), got ${parsed.get(3)}`);
    } else {
      bad('the partly stock-fulfilled line is quoted at its PENDING remainder',
        'the line was dropped entirely instead of being quoted for the 5 still to buy');
    }

    const excl = psql(`
      SELECT string_agg(line_no || '=' || reason, ' | ' ORDER BY line_no)
        FROM proc.rfq_line_exclusions WHERE rfq_id = ${lit(rfqId)}::uuid;`);
    if (excl) ok('every dropped line is recorded with a reason', excl);
    else bad('every dropped line is recorded with a reason', 'the exclusion ledger is empty');
    if (/2=held/.test(excl || '')) ok('including the HELD line, with its reason');
    else bad('including the HELD line, with its reason', `exclusions: ${excl}`);
  }

  // ── 2. dispatch + time-bound token ──────────────────────────────────────
  console.log('\n--- 2. proof: dispatch mints a hashed, time-bound link ---');
  if (rfqId) {
    // Vendors need an email before a dispatch can reach them (F1).
    const needEmail = psql(`
      SELECT string_agg(v.vendor_code, ',')
        FROM proc.rfq_invitations i JOIN core.vendors v ON v.id = i.vendor_id
       WHERE i.rfq_id = ${lit(rfqId)}::uuid
         AND NULLIF(btrim(coalesce(v.contact_email,'')),'') IS NULL;`);
    if (needEmail) {
      const blocked = await api(`/rfq/${rfqId}/dispatch`, { method: 'POST', token: procurement, body: {} });
      if (blocked.status >= 400 && /no email/i.test(String(blocked.data?.message || ''))) {
        ok('a dispatch to a vendor with no email is REFUSED, not silently skipped',
          String(blocked.data?.message).slice(0, 70));
      } else {
        bad('a dispatch to a vendor with no email is REFUSED', `status ${blocked.status}`);
      }
      psql(`SELECT set_config('app.vendor_change_token','harness','false');
            UPDATE core.vendors SET contact_email = 'w5f.harness@example.com'
             WHERE id IN (SELECT vendor_id FROM proc.rfq_invitations WHERE rfq_id=${lit(rfqId)}::uuid);`);
      ok('(harness then supplies an email so the dispatch can proceed)');
    } else {
      ok('every invited vendor already has an email on file');
    }

    const disp = await api(`/rfq/${rfqId}/dispatch`, { method: 'POST', token: procurement, body: { channel: 'manual' } });
    if (disp.status >= 400) {
      bad('the one-click dispatch succeeds', `status ${disp.status} ${disp.text.slice(0, 200)}`);
    } else {
      ok('the one-click dispatch succeeds', `${disp.data?.recipients} recipient(s)`);
      ok('it reports the transport honestly',
        String(disp.data?.transport || '').slice(0, 60));
      eq('and does not claim delivery it cannot prove', disp.data?.delivered, 0);

      const outbox = psql(`SELECT count(*)::int || '|' || count(*) FILTER (WHERE state='pending')::int
                             FROM core.email_outbox WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      ok('and every message is in the outbox', outbox);

      // The raw token must not be recoverable from the database.
      const expiries = psql(`
        SELECT count(*) FILTER (WHERE expires_at > now())::text || '|' || count(*)::text
          FROM proc.rfq_invitations WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      ok('every invitation carries a future expiry', expiries);
    }
  }

  // Mint a token for the sandbox proofs, the way dispatch would.
  const invite = psql(`
    SELECT i.id || '|' || i.vendor_id FROM proc.rfq_invitations i
     WHERE i.rfq_id = ${lit(rfqId)}::uuid ORDER BY i.vendor_id LIMIT 1;`).trim();
  if (invite) {
    const [invitationId, vendorId] = invite.split('|');
    const { createHash, randomBytes } = await import('node:crypto');
    const raw = randomBytes(32).toString('base64url');
    psql(`UPDATE proc.rfq_invitations
             SET token_hash = ${lit(createHash('sha256').update(raw).digest('hex'))}::text,
                 expires_at = now() + interval '72 hours'
           WHERE id = ${lit(invitationId)}::uuid;`);
    tokenA = raw;
    tokenB = raw;

    // Another vendor, to prove the sandbox really is a sandbox.
    const other = psql(`
      SELECT i.id || '|' || i.vendor_id FROM proc.rfq_invitations i
       WHERE i.rfq_id = ${lit(rfqId)}::uuid AND i.vendor_id <> ${lit(vendorId)}::uuid
       ORDER BY i.vendor_id LIMIT 1;`).trim();
    if (other) {
      const [oInv, oVendor] = other.split('|');
      const raw2 = randomBytes(32).toString('base64url');
      psql(`UPDATE proc.rfq_invitations
               SET token_hash = ${lit(createHash('sha256').update(raw2).digest('hex'))}::text,
                   expires_at = now() + interval '72 hours'
             WHERE id = ${lit(oInv)}::uuid;`);
      tokenB = raw2;
      createdVendorIds.push(oVendor);
    }

    // ── 3. the sandbox ────────────────────────────────────────────────────
    console.log('\n--- 3. proof: the portal shows one vendor their lines and nothing else ---');
    const pack = await api(`/vendor-portal/${tokenA}`);
    if (pack.status !== 200) {
      bad('the token portal opens with no login at all', `status ${pack.status} ${pack.text.slice(0, 160)}`);
    } else {
      ok('the token portal opens with no login at all', pack.data?.rfq?.number);
      eq('and the vendor is identified by that token alone', !!pack.data?.vendor?.code, true);
      const nLines = (pack.data?.lines || []).length;
      if (nLines > 0) ok('it returns the assigned lines', `${nLines} line(s)`);
      else bad('it returns the assigned lines', 'the pack is empty — the vendor sees nothing to quote');
      if (!pack.data?.pr) ok('and carries no purchase-requisition object');
      else bad('and carries no purchase-requisition object', 'the pack leaked PR data');
      const dump = JSON.stringify(pack.data);
      if (/total_amount|budget|pr_number/i.test(dump)) {
        bad('the payload leaks nothing beyond the pack', dump.slice(0, 200));
      } else ok('the payload leaks no budget or PR fields');

      const packB = await api(`/vendor-portal/${tokenB}`);
      if (packB.status === 200 && packB.data?.vendor?.code !== pack.data?.vendor?.code) {
        ok('a different token is a different vendor', `${pack.data?.vendor?.code} vs ${packB.data?.vendor?.code}`);
      } else {
        finding('could not compare two vendors', 'only one invitation existed on this RFQ');
      }

      // A forged token must not resolve.
      const forged = await api(`/vendor-portal/${'a'.repeat(43)}`);
      if (forged.status === 404) ok('a forged token is refused', '404');
      else bad('a forged token is refused', `status ${forged.status}`);

      // ── 4. the Excel round trip ────────────────────────────────────────
      console.log('\n--- 4. proof: the template is a real .xlsx and reads back ---');
      const tpl = await fetch(`${API}/vendor-portal/${tokenA}/template.xlsx`);
      if (tpl.status !== 200) {
        bad('the template downloads', `status ${tpl.status}`);
      } else {
        const buf = Buffer.from(await tpl.arrayBuffer());
        // ZIP magic: "PK\x03\x04". A renamed CSV would fail here, which is the
        // whole point of checking rather than trusting the file extension.
        if (buf[0] === 0x50 && buf[1] === 0x4b && buf[2] === 0x03 && buf[3] === 0x04) {
          ok('the template is a real ZIP/OOXML package', `PK\\x03\\x04, ${buf.length} bytes`);
        } else {
          bad('the template is a real ZIP/OOXML package', `magic ${buf.slice(0, 4).toString('hex')}`);
        }
        const ctype = tpl.headers.get('content-type') || '';
        if (ctype.includes('spreadsheetml')) ok('served with the xlsx content type', ctype);
        else bad('served with the xlsx content type', ctype);

        // Round trip: fill the prices in and re-upload as the vendor would.
        const filled = await fillTemplate(buf);
        if (filled) {
          const up = await api(`/vendor-portal/${tokenA}/upload`, {
            method: 'POST',
            raw: { body: filled, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' },
            headers: { 'x-file-name': 'w5f-quotation.xlsx' },
          });
          if (up.status >= 400 && up.status !== 400) {
            bad('the filled workbook is accepted', `status ${up.status} ${up.text.slice(0, 200)}`);
          } else if (up.status === 400) {
            bad('the filled workbook is accepted', `rejected: ${up.text.slice(0, 200)}`);
          } else {
            ok('the filled workbook is accepted', `v${up.data?.version}`);
            const stored = psql(`SELECT count(*) FROM proc.quotations
                                  WHERE rfq_id=${lit(rfqId)}::uuid AND vendor_id=${lit(vendorId)}::uuid;`);
            if (Number(stored) >= 1) ok('and a quotation version was recorded', `${stored} version(s)`);
            else bad('and a quotation version was recorded', 'none in the database');
          }
        }
      }

      // ── 5. revisions do not erase ──────────────────────────────────────
      console.log('\n--- 5. proof: re-uploading appends a version and keeps the old one ---');
      const again = await api(`/vendor-portal/${tokenA}/quote`, {
        method: 'POST',
        body: {
          lines: (pack.data?.lines || []).map((l) => ({ lineNo: l.line_no, unitPrice: 999 })),
          // Restated on the revision, because a vendor revising a quote restates
          // its terms. Sending price alone would supersede the version that
          // carries the lead time and payment terms, leaving the comparative
          // matrix reading a live quote with none — an artefact of the fixture,
          // not a fact about the vendor.
          leadTimeDays: 10,
          warrantyMonths: 12,
          paymentTerms: '30 days from invoice',
          validityDays: 30,
          taxesIncluded: true,
          notes: 'harness revision',
        },
      });
      if (again.status >= 400) {
        bad('a second submission is accepted', `status ${again.status} ${again.text.slice(0, 180)}`);
      } else {
        ok('a second submission is accepted', `v${again.data?.version}`);
        const hist = psql(`
          SELECT string_agg(version || ':' || state, ',' ORDER BY version)
            FROM proc.quotations WHERE rfq_id=${lit(rfqId)}::uuid AND vendor_id=${lit(vendorId)}::uuid;`);
        ok('and both versions are on record', hist);
        const v1 = /(^|,)1:/.test(`,${hist}`);
        if (v1) ok('version 1 is still readable after being superseded');
        else bad('version 1 is still readable after being superseded', hist);
      }

      // Expiry: a token in the past must be refused, and must say why.
      //
      // invited_at is moved BACK as well. rfq_invitations_expiry_after_invite
      // requires expires_at > invited_at, so simply setting expires_at into the
      // past trips that rule instead of simulating a lapsed link — the harness
      // was fighting its own migration.
      psql(`UPDATE proc.rfq_invitations
               SET invited_at = now() - interval '3 days',
                   expires_at = now() - interval '1 day'
             WHERE id = ${lit(invitationId)}::uuid;`);
      const expired = await api(`/vendor-portal/${tokenA}`);
      if (expired.status === 403 && /expired/i.test(String(expired.data?.message || ''))) {
        ok('an expired link is refused with an explanation', String(expired.data?.message).slice(0, 60));
      } else {
        bad('an expired link is refused', `status ${expired.status} ${expired.text.slice(0, 140)}`);
      }
      psql(`UPDATE proc.rfq_invitations
               SET invited_at = now() - interval '1 hour',
                   expires_at = now() + interval '72 hours'
             WHERE id = ${lit(invitationId)}::uuid;`);
    }
  }

  // ── 6. comparative matrix, split awards, negotiation, PDF ───────────────
  console.log('\n--- 6. proof: split awards and offline negotiation ---');
  if (rfqId) {
    const cs = await api(`/pr/${prId}/cs`, { method: 'POST', token: procurement, body: {} });
    if (cs.status >= 400) {
      finding('a comparative statement could not be built for the fixture', `status ${cs.status}`);
    } else {
      csId = cs.data?.id || cs.data?.cs?.id;
      ok('a comparative statement is generated', csId);

      if (csId) {
        const m0 = await api(`/cs/${csId}/matrix`, { token: procurement });
        if (m0.status === 200) {
          // NOT a tautology: printing the count and calling it a pass would be
          // green for an empty matrix, which is exactly what a CS with no rfq_id
          // produces. The matrix must actually carry the RFQ's lines.
          const total = Number(m0.data?.total_lines ?? 0);
          if (total > 0) ok('the matrix reads back', `${total} line(s)`);
          else bad('the matrix reads back', '0 lines — the CS is not linked to an RFQ');
          const hasTerms = (m0.data?.lines || []).some((l) =>
            (l.bids || []).some((b) => b.lead_time_days !== null || b.payment_terms !== null));
          if (hasTerms) ok('and carries delivery and payment terms alongside price');
          else finding('no bid carries lead time or payment terms', 'matrix columns exist but are empty');
        } else bad('the matrix reads back', `status ${m0.status} ${m0.text.slice(0, 200)}`);

        const v1 = psql(`SELECT id FROM core.vendors WHERE vendor_code='V-00082';`).trim();
        const v2 = psql(`SELECT id FROM core.vendors WHERE vendor_code='V-00086';`).trim();
        if (csId && v1 && v2) {
          const lineNo = Number(psql(`SELECT min(line_no) FROM proc.rfq_lines WHERE rfq_id=${lit(rfqId)}::uuid;`));
          const a1 = await api(`/cs/${csId}/award`, {
            method: 'POST', token: procurement,
            body: { lineNo, vendorId: v1, qty: 1, justification: 'Harness: first award' },
          });
          if (a1.status >= 400) bad('a line can be awarded', `status ${a1.status} ${a1.text.slice(0, 180)}`);
          else ok('a line is awarded', `line ${lineNo} -> V-00082, round ${a1.data?.award_round}`);

          const noJust = await api(`/cs/${csId}/award`, {
            method: 'POST', token: procurement, body: { lineNo, vendorId: v2, qty: 1, justification: '  ' },
          });
          if (noJust.status === 400) ok('an award with no justification is refused');
          else bad('an award with no justification is refused', `status ${noJust.status}`);

          const a2 = await api(`/cs/${csId}/award`, {
            method: 'POST', token: procurement,
            body: { lineNo, vendorId: v2, qty: 1, justification: 'Harness: re-award to the other vendor' },
          });
          if (a2.status >= 400) bad('the line can be RE-awarded to a different vendor', `status ${a2.status} ${a2.text.slice(0, 180)}`);
          else {
            ok('the line is RE-awarded to a different vendor', `round ${a2.data?.award_round}`);
            const live = psql(`SELECT count(*) FROM proc.cs_line_awards
                                WHERE cs_id=${lit(csId)}::uuid AND rfq_line_no=${lineNo} AND superseded_at IS NULL;`);
            eq('and exactly ONE award is live for that line', live, '1');
            const history = psql(`SELECT count(*) FROM proc.cs_line_awards
                                   WHERE cs_id=${lit(csId)}::uuid AND rfq_line_no=${lineNo};`);
            eq('while the earlier award is retained', history, '2');
            const superseded = psql(`SELECT coalesce(supersede_reason,'(none)') FROM proc.cs_line_awards
                                       WHERE cs_id=${lit(csId)}::uuid AND rfq_line_no=${lineNo} AND superseded_at IS NOT NULL;`);
            if (/Harness/.test(superseded)) ok('and records why it changed', superseded);
            else bad('and records why it changed', superseded);
          }

          const inAudit = psql(`SELECT count(*) FROM audit.audit_log
                                 WHERE action='cs_line_award' AND reason LIKE 'Harness%';`);
          if (Number(inAudit) >= 2) ok('and both awards are in the immutable trail', `${inAudit} entries`);
          else bad('and both awards are in the immutable trail', `found ${inAudit}`);
        }

        // The negotiation must target a vendor that ALREADY quoted, or the
        // "increments the version" claim is not actually exercised — a vendor
        // with no prior quote legitimately produces v1 and an empty before-image,
        // which would pass while proving nothing about version control.
        const quotedVendorId = psql(`SELECT q.vendor_id FROM proc.quotations q
                                       WHERE q.rfq_id=${lit(rfqId)}::uuid AND q.state='Submitted'
                                       ORDER BY q.version DESC LIMIT 1;`).trim();
        const negVendor = quotedVendorId || v1;

        const noJustNeg = await api(`/rfq/${rfqId}/negotiate`, {
          method: 'POST', token: procurement,
          body: { vendorId: negVendor, justification: '', source: 'phone', lines: [{ lineNo: 1, unitPrice: 100 }] },
        });
        if (noJustNeg.status === 400) ok('a phone-negotiated rate with no justification is refused');
        else bad('a phone-negotiated rate with no justification is refused', `status ${noJustNeg.status}`);

        const neg = await api(`/rfq/${rfqId}/negotiate`, {
          method: 'POST', token: procurement,
          body: {
            vendorId: negVendor, source: 'phone',
            justification: 'Harness: agreed on a call, 5% off for a 30-day term',
            lines: [{ lineNo: 1, unitPrice: 1234 }],
            leadTimeDays: 21,
          },
        });
        if (neg.status >= 400) bad('a phone-negotiated rate is recorded', `status ${neg.status} ${neg.text.slice(0, 200)}`);
        else {
          ok('a phone-negotiated rate is recorded', `v${neg.data?.version}`);
          // THE REQUIREMENT: "automatically incrementing versions (v2, v3)".
          // A negotiated rate that lands on v1 has not incremented anything.
          const priorVersion = quotedVendorId
            ? Number(psql(`SELECT max(version) FROM proc.quotations
                            WHERE rfq_id=${lit(rfqId)}::uuid AND vendor_id=${lit(negVendor)}::uuid
                              AND id <> ${lit(String(neg.data?.quotation_id || ''))}::uuid;`))
            : 0;
          if (quotedVendorId && Number(neg.data?.version) === priorVersion + 1) {
            ok('and it INCREMENTS the vendor\u2019s own version rather than restarting', `v${priorVersion} \u2192 v${neg.data?.version}`);
          } else if (!quotedVendorId) {
            finding('no vendor had quoted before the call', 'so no version increment could be shown');
          } else {
            bad('and it INCREMENTS the vendor\u2019s own version rather than restarting', `was v${priorVersion}, produced v${neg.data?.version}`);
          }
          const before = JSON.stringify(neg.data?.rate_before || {});
          const after = JSON.stringify(neg.data?.rate_after || {});
          if (before !== '{}') ok('and the previous rates are preserved', before.slice(0, 60));
          else finding('no previous rate was on file', 'so the before-image is empty');
          ok('with the new rate', after.slice(0, 60));
          const nlog = psql(`SELECT count(*) FROM negotiation_log
                              WHERE rfq_id=${lit(rfqId)}::uuid AND source='phone';`);
          if (Number(nlog) > 0) ok('and a negotiation_log row exists', `${nlog}`);
          else bad('and a negotiation_log row exists', 'none');
          const naudit = psql(`SELECT count(*) FROM audit.audit_log
                                WHERE action='phone_negotiation' AND reason LIKE 'Harness%';`);
          if (Number(naudit) > 0) ok('and the justification is in the immutable trail', `${naudit} entry`);
          else bad('and the justification is in the immutable trail', 'none');
        }

        // ── 7. the PDF ───────────────────────────────────────────────────
        console.log('\n--- 7. proof: the statement compiles to a UUID-named PDF on disk ---');
        const pdf = await api(`/cs/${csId}/pdf`, { method: 'POST', token: procurement, body: {} });
        if (pdf.status >= 400) bad('the statement compiles to a PDF', `status ${pdf.status} ${pdf.text.slice(0, 200)}`);
        else {
          ok('the statement compiles to a PDF', `${pdf.data?.bytes} bytes`);
          if (/^[0-9a-f-]{36}$/.test(String(pdf.data?.document_id || ''))) ok('named by UUID, not by CS number', pdf.data?.document_id);
          else bad('named by UUID, not by CS number', String(pdf.data?.document_id));
          if (String(pdf.data?.object_key || '').endsWith('.pdf')) ok('stored with a .pdf key', pdf.data?.object_key);
          else bad('stored with a .pdf key', String(pdf.data?.object_key));

          let root = resolve(REPO, 'var', 'documents');
          for (const cand of [resolve(REPO, 'var', 'documents'), resolve(REPO, 'apps', 'var', 'documents')]) {
            if (existsSync(cand)) { root = cand; break; }
          }
          const abs = join(root, String(pdf.data?.object_key));
          if (existsSync(abs)) {
            docFile = abs;
            const head = readFileSync(abs).subarray(0, 5).toString('latin1');
            if (head.startsWith('%PDF-')) ok('and the file on disk is a real PDF', `${statSync(abs).size} bytes`);
            else bad('and the file on disk is a real PDF', `header "${head}"`);
            const raw = readFileSync(abs).toString('latin1');
            if (/%%EOF/.test(raw)) ok('and it is terminated properly');
            else bad('and it is terminated properly', 'no %%EOF marker');
          } else {
            bad('and the file is actually on disk', `not found: ${abs}`);
          }

          // A recompile must not overwrite an issued document.
          const again2 = await api(`/cs/${csId}/pdf`, { method: 'POST', token: procurement, body: {} });
          if (again2.data?.document_id && again2.data.document_id !== pdf.data.document_id) {
            ok('recompiling issues a NEW document rather than overwriting', again2.data?.document_id);
            const abs2 = join(root, String(again2.data?.object_key));
            if (existsSync(abs2)) docFile = [docFile, abs2].filter(Boolean).join(';');
          } else {
            bad('recompiling issues a NEW document', 'the same document_id came back');
          }
        }
      }
    }
  }

  // ── 8. the web must not serve the documents or the outbox ───────────────
  console.log('\n--- 8. proof: stored artefacts are not web-served ---');
  for (const p of ['/var/outbox/anything.eml', '/var/documents/anything.pdf', '/../var/outbox/x.eml']) {
    const r = await fetch(`${WEB}${p}`);
    if (r.status === 404 || r.status === 400) ok(`web refuses ${p}`, String(r.status));
    else bad(`web refuses ${p}`, `status ${r.status}`);
  }
} finally {
  console.log('\n--- cleanup ---');
  // Order matters: rfq_lines references pr_lines, so the RFQ has to go first or
  // the line delete fails on a foreign key and the PR is left behind.
  if (rfqId) {
    try {
      psql(`DELETE FROM core.email_outbox WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      psql(`DELETE FROM proc.negotiation_log WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      psql(`DELETE FROM proc.quotations WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      psql(`DELETE FROM proc.rfq_invitations WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      psql(`DELETE FROM proc.rfq_line_exclusions WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      psql(`DELETE FROM proc.rfq_lines WHERE rfq_id = ${lit(rfqId)}::uuid;`);
      psql(`DELETE FROM proc.rfq WHERE id = ${lit(rfqId)}::uuid;`);
      ok('the harness RFQ, its invitations, quotes, negotiations and outbox are gone');
    } catch (e) { bad('clean the RFQ fixture', String(e.message).slice(0, 140)); }
  }
  if (csId) {
    try {
      psql(`DELETE FROM proc.cs_line_awards WHERE cs_id = ${lit(csId)}::uuid;`);
      psql(`DELETE FROM proc.cs_lines WHERE cs_id = ${lit(csId)}::uuid;`);
      ok('the harness line awards are gone');
    } catch (e) { bad('clean the CS awards', String(e.message).slice(0, 140)); }
  }
  if (prId) {
    try {
      psql(`DELETE FROM proc.pr_lines WHERE pr_id = ${lit(prId)}::uuid;`);
      psql(`DELETE FROM proc.comparative_statements WHERE pr_id = ${lit(prId)}::uuid;`);
      psql(`DELETE FROM proc.purchase_requisitions WHERE id = ${lit(prId)}::uuid;`);
      ok('the harness PR and its lines are gone');
    } catch (e) { bad('clean the PR fixture', String(e.message).slice(0, 140)); }
  }
  // Sweep ANY PR this harness ever left behind, not just this run's. An earlier
  // run aborted between the RFQ insert and the line snapshot, and a per-run
  // cleanup cannot see that; the final assertion then fails on someone else's
  // debris and the failure points at the wrong place.
  try {
    const strays = psql(`
      SELECT string_agg(id::text, ',') FROM proc.purchase_requisitions WHERE pr_number LIKE 'PR-W5F-%';`);
    if (strays) {
      // ORDER MATTERS, and it was wrong. This swept rfq_lines BEFORE
      // quotation_lines, but every PR this harness creates carries vendor
      // quotations — quotation_lines.rfq_line_fkey then refuses the delete.
      // The sweep only ever appeared to work because it usually found nothing
      // to sweep; the first stray it did find it could not remove, so it left
      // the stray in place and failed. Self-perpetuating.
      //
      // Each statement runs independently: one refusal must not abort the rest
      // and strand the PR that the final assertion then reports as surviving.
      const ids = strays.split(',');
      for (const id of ids) {
        const step = (sql) => {
          try { psql(sql); }
          catch (e) { bad(`sweep step for PR ${id}`, String(e?.message).split('\n')[0].slice(0, 160)); }
        };
        // W5-H added these; a swept PR may carry orders from a PO generation.
        step(`DELETE FROM proc.purchase_order_lines WHERE pr_line_id IN (SELECT id FROM proc.pr_lines WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.pr_line_po_exclusions WHERE pr_line_id IN (SELECT id FROM proc.pr_lines WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.purchase_orders WHERE pr_id = ${lit(id)}::uuid;`);
        step(`DELETE FROM core.email_outbox WHERE rfq_id IN (SELECT id FROM proc.rfq WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.negotiation_log WHERE rfq_id IN (SELECT id FROM proc.rfq WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.quotation_lines WHERE rfq_id IN (SELECT id FROM proc.rfq WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.quotations WHERE rfq_id IN (SELECT id FROM proc.rfq WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.rfq_invitations WHERE rfq_id IN (SELECT id FROM proc.rfq WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.rfq_line_exclusions WHERE pr_line_id IN (SELECT id FROM proc.pr_lines WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.rfq_lines WHERE rfq_id IN (SELECT id FROM proc.rfq WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.rfq WHERE pr_id = ${lit(id)}::uuid;`);
        step(`DELETE FROM proc.cs_line_awards WHERE cs_id IN (SELECT id FROM proc.comparative_statements WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.cs_lines WHERE cs_id IN (SELECT id FROM proc.comparative_statements WHERE pr_id = ${lit(id)}::uuid);`);
        step(`DELETE FROM proc.comparative_statements WHERE pr_id = ${lit(id)}::uuid;`);
        step(`DELETE FROM proc.pr_lines WHERE pr_id = ${lit(id)}::uuid;`);
        step(`DELETE FROM proc.purchase_requisitions WHERE id = ${lit(id)}::uuid;`);
      }
      ok('and any PR left by an earlier aborted run is swept too', `${ids.length} row(s)`);
    } else {
      ok('and no earlier run left a PR behind');
    }
  } catch (e) { bad('sweep earlier harness PRs', String(e.message).slice(0, 140)); }
  if (docFile) {
    let removed = 0;
    for (const f of String(docFile).split(';').filter(Boolean)) {
      if (existsSync(f)) { try { unlinkSync(f); removed++; } catch { /* ignore */ } }
    }
    ok('the compiled PDFs are removed', `${removed}`);
  }

  const left = psql(`
    SELECT (SELECT count(*) FROM proc.purchase_requisitions WHERE pr_number LIKE 'PR-W5F-%')::text || '|' ||
           (SELECT count(*) FROM core.email_outbox WHERE created_at > now() - interval '2 hours')::text;`);
  if (left === '0|0') ok('no harness PR and no harness outbox rows survive', left);
  else bad('no harness PR and no harness outbox rows survive', left);

  const added = Number(psql('SELECT count(*) FROM audit.audit_log;')) - auditBefore;
  ok('audit entries this run added are permanent, by design', `${added} row(s)`);
  const chain = psql(`SELECT COALESCE(first_bad_id::text,'clean') FROM audit.fn_verify_audit_chain();`);
  eq('and the hash chain is still clean', chain, 'clean');
}

console.log(`\n${fail} failed, ${pass} passed, ${findings} finding(s)\n`);
process.exit(fail > 0 ? 1 : 0);

// ─── helpers ────────────────────────────────────────────────────────────────
/**
 * Fill the downloaded template the way a vendor would, and hand back the bytes.
 *
 * It parses the template with the API's OWN reader and re-emits it with the API's
 * OWN writer, so the round trip exercises the same code the upload endpoint uses
 * rather than a second implementation that might agree with itself. An earlier
 * version of this function returned null and the upload check was therefore
 * never reached — a silently skipped test that read like a passing one.
 */
async function fillTemplate(tplBuf) {
  const { readXlsx, buildXlsx } = await import(
    new URL('../apps/api/dist/vendor-portal/xlsx.js', import.meta.url).href
  );

  const sheet = readXlsx(tplBuf);
  const headIdx = sheet.rows.findIndex((r) => r.some((c) => String(c ?? '').trim().toLowerCase() === 'line'));
  if (headIdx < 0) return null;
  const head = sheet.rows[headIdx];
  const iLine = head.findIndex((c) => String(c ?? '').trim().toLowerCase() === 'line');
  const iPrice = head.findIndex((c) => String(c ?? '').trim().toLowerCase() === 'unit price');
  const iLead = head.findIndex((c) => String(c ?? '').trim().toLowerCase() === 'lead time (days)');
  const iWarr = head.findIndex((c) => String(c ?? '').trim().toLowerCase() === 'warranty (months)');
  const iTerms = head.findIndex((c) => String(c ?? '').trim().toLowerCase() === 'payment terms');
  const iValid = head.findIndex((c) => String(c ?? '').trim().toLowerCase() === 'validity (days)');
  const iTax = head.findIndex((c) => String(c ?? '').trim().toLowerCase() === 'taxes included');
  if (iLine < 0 || iPrice < 0) return null;

  // The commercial terms are filled in as well as the price. Without them the
  // comparative matrix's lead-time and payment-terms columns stay NULL and the
  // F7 proof degrades into "the columns exist but nothing can populate them".
  // Columns are matched by header name and skipped when the template lacks them,
  // so this does not assume a fixed column order.
  const put = (copy, idx, value) => { if (idx >= 0) copy[idx] = value; };

  // Price only the real lines — the trailing note rows have no line number.
  let price = 500;
  const rows = sheet.rows.map((r, ri) => {
    if (ri <= headIdx) return r;
    const n = Number(r[iLine]);
    if (!Number.isFinite(n) || n <= 0) return r;
    const copy = [...r];
    put(copy, iPrice, price);
    put(copy, iLead, 14);
    put(copy, iWarr, 12);
    put(copy, iTerms, '30 days from invoice');
    put(copy, iValid, 45);
    put(copy, iTax, 'Yes');
    price += 100;
    return copy;
  });

  return buildXlsx({ name: 'Quotation', rows });
}
